import type { Metadata } from "next";
import { pressStart2P } from '@/app/ui/fonts';
import './global.css';
import Background from "@/app/ui/background";

export const metadata: Metadata = {
  title: "Steward's Quest | Educational Game Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pressStart2P.className} antialiased bg-black`}
      >
        <Background>
          {children}
        </Background>
      </body>
    </html>
  );
}
